public  class SalesforceDeveloper {
    public void  myFavorite(){
        integer favoriNumaram=6;
        system.debug(favoriNumaram);
        string favoriSehir='Edmonton';
        system.debug(favoriSehir);
        
        string fullName =favoriNumaram + ' ' +favoriSehir ;
        
        system.debug('favori numaram'+' '+favoriNumaram +' '+'favori sehrim'+' ' +favoriSehir);

       
        
 
       
  }
}